name: LifeSteal
version: ${project.version}
main: me.sirhenry.lifesteal.LifeSteal
api-version: 1.19
authors: [ Purpele4k ]
description: Allows Players to Steal Hearts from Eachother by Killing.
website:
commands:
  withdraw:
    description: Allows you to give your hearts to other people
